query Home {
	projects {
    title
    slug
    id
    date
    cover {
      url
    }
  }
  about {
    text_intro
    text_body
    cover {
      url
    }
  }
  experiences {
    title
    role
    top
    description
    year
  }
}